-- First, add the dude column if it doesn't exist
ALTER TABLE oficinas ADD COLUMN IF NOT EXISTS dude VARCHAR(50);

-- Insert office data
INSERT INTO oficinas (cod_oficina, nombre, tipo_sitio, dude, direccion, ciudad, zona) VALUES
('145036', 'PV CAMPANARIO FRENTE A YUMBO', 'PUNTO DE VENTA', NULL, 'C.C. CAMPANARIO BURBUJA FRENTE A JUMBO', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('101108', 'PV Acertemos Calle 6ta', 'PUNTO DE VENTA', NULL, 'Cll 6 # 9-51 local 3', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('145022', 'P.V BATALLON KIOSKO', 'PUNTO DE VENTA', 'si', 'CARRERA 15 # 3 NORTE - 66', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('163015', 'PV. ACERTEMOS VILLA DEL VIENTO', 'PUNTO DE VENTA', NULL, 'Calle 56 N 10-10', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('129050', 'PV LOMAS DE COMFACAUCA POPAYAN', 'OFICINA', 'si', 'Cra 49 Cll 2 40 -1', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('128007', 'P.V CIUDADELA SAN EDUARDO', 'PUNTO DE VENTA', 'si', 'CL 70B N CRA 8C-93 SAN EDUARDO', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('154004', 'PV.CAMILO TORRES', 'PUNTO DE VENTA', 'si', 'CRA 9 CL 5-13 CENTRO', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('145013', 'PV ACERTEMOS CAMPANARIO', 'PUNTO DE VENTA', 'si', 'CARRERA 9 CALLE 24AN 21 BARRIO CENTRO COMERCIAL CAMPANARIO', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('136001', 'OF.SAN AGUSTIN', 'OFICINA', 'si', 'CARRERA 7 CALLE 6-42 PISO 2 CENTRO', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('128001', 'O.F PARQUE PPAL LA PAZ', 'OFICINA', NULL, 'CALLE 70 # 7-19', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('145001', 'Of Los Hoyos Popayan', 'PUNTO DE VENTA', 'si', 'Carrera 6 # 27 CN 35', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('136020', 'ACERTEMOS ANARKOS', 'PUNTO DE VENTA', 'si', 'CRA 6 #5-90', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('136017', 'PARQUE CALDAS', 'PUNTO DE VENTA', 'si', 'CRA 7 # 4 - 64 BARRIO CENTRO PARQUE CALDAS', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('149001', 'OF JOSE MARIA OBANDO', 'OFICINA', 'si', 'CALLE 7 22-48 PI 1 B/JOSE MARIA OBANDO', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('165007', 'PV GRANERO MONTERREY', 'PUNTO DE VENTA', 'si', 'CALLE 5 30-190 PISO 1 LOCAL 101', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('149006', 'ESMERALDA CALLE 5', 'PUNTO DE VENTA', 'si', 'Calle 5 # 22A-05 ESMERALDA', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('145027', 'ACERTEMOS SAN MARTIN', 'PUNTO DE VENTA', NULL, 'Calle 18N #7-40 Ciudad Jardin', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('165008', 'PV SAN JOSE', 'PUNTO DE VENTA', 'si', 'Calle 6 # 33 - 03 LOCAL 3 ESQUINA', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('134034', 'Pv Olimpica Modelo Popayan', 'PUNTO DE VENTA', NULL, 'Carrera 7 # 2N Esquina', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('154013', 'Pv Valla Doli', 'PUNTO DE VENTA', NULL, 'Carrera 32 # 20-05', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('179002', 'Pv2 Glorieta La Chirimia', 'PUNTO DE VENTA', NULL, 'Carrera 17 # 12 - 145', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE'),
('138022', 'PV SINDICAL', 'PUNTO DE VENTA', 'si', 'Carrera 9 # 19-29', 'POPAYAN', 'ZONA CENTRO SUR ORIENTE');
